<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250422212753 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE lignefacture (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, prixht DOUBLE PRECISION NOT NULL, tva DOUBLE PRECISION NOT NULL, facture_id INT NOT NULL, produit_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_216F1FD57F2DEE08 ON lignefacture (facture_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_216F1FD5F347EFB ON lignefacture (produit_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE produit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, prixht DOUBLE PRECISION NOT NULL, tva DOUBLE PRECISION NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1D1C63B3C8121CE9 ON utilisateur (nom_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE lignefacture ADD CONSTRAINT FK_216F1FD57F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE lignefacture ADD CONSTRAINT FK_216F1FD5F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3C8121CE9 FOREIGN KEY (nom_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE lignefacture DROP CONSTRAINT FK_216F1FD57F2DEE08
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE lignefacture DROP CONSTRAINT FK_216F1FD5F347EFB
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B3C8121CE9
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE lignefacture
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE produit
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE utilisateur
        SQL);
    }
}
